name: workplan_beta_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.21+20

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  flutter_form_builder: ^6.0.1
  flutter_launcher_icons: ^0.9.0
  js: ^0.6.3
  datetime_picker_formfield: ^2.0.0
  ionicons: ^0.1.2
  intro_slider: ^2.4.3
  camera: ^0.8.1+3
  image_cropper: ^1.4.0
  radio_button_form_field: ^0.0.4
  camera_camera: ^2.0.2
  google_maps_flutter: ^2.0.6
  geolocator: ^7.2.0+1
  http: ^0.13.3
  # firebase_crashlytics: ^2.0.6
  # firebase_core: ^1.1.0
  # firebase_messaging: ^10.0.2
  # toast: ^0.1.5
  crypto: ^3.0.1
  shared_preferences: ^2.0.6
  webview_flutter: ^2.0.8
  fluttertoast: ^8.0.7
  badges: ^2.0.1
  location_permissions: ^4.0.0
  location: ^4.3.0
  geocoding: ^2.0.4
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  form_field_validator: ^1.1.0
  mask_text_input_formatter: ^2.0.0
  # get_version: any
  flutter_local_notifications: ^8.2.0
  rxdart: any
  workmanager: any
  overlay_support: any
  image_picker: ^0.8.5
  marquee: ^2.2.0
  local_auth: ^1.1.8
  intl: ^0.17.0
  dio: ^4.0.1
  cached_network_image: ^3.1.0+1
  currency_text_input_formatter: ^2.1.5
  flutter_countdown_timer: ^4.1.0
  unique_identifier: ^0.2.2
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.0.2
  flutter_app_name: ^0.1.1
  package_info_plus: ^1.4.0
  trust_location: ^2.0.13
  datetime_setting: ^2.0.1
  safe_device: ^1.1.1
  # fake_gps_detector: ^0.5.1
  # permission_handler: ^9.2.0

flutter_app_name:
  name: "WrkPln"

flutter_native_splash:
  color: '#ffffff'
  image: images/App_Splash/iconSplashScreen.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "images/App_Splash/icon launcher.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/App_Splash/
    - assets/
    # - assets/img_gojek_logo.png
    # - assets/img_greenhcm_logo.png
    # - assets/icons/icon_menu.png
    # - assets/icons/icon_saldo.png
    # - assets/icons/icon_scan.png
    # - assets/icons/icon_transfer.png
    # - assets/photo_camera_test.png
    # - assets/images/food_1.jpg
    # - assets/images/food_2.jpg
    # - assets/images/food_3.jpg
    # - assets/images/food_4.jpg
    # - assets/images/food_5.jpg
    # - assets/images/promo_1.jpg
    # - assets/images/promo_2.jpg
    # - assets/images/promo_3.jpg
    # - assets/images/promo_4.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NeoSans
      fonts:
        - asset: assets/fonts/NeoSansStd-Regular.otf
    - family: NeoSansBold
      fonts:
        - asset: assets/fonts/NeoSansStd-Bold.otf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
